# Generated by Django 6.0.7 on 2026-08-03 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('ANOMALY', 'Anomaly Detection'), ('HEALTH', 'Health Score'), ('PREDICTION', 'Trend Prediction'), ('EXPLANATION', 'AI Explanation')], default='ANOMALY', max_length=15)),
                ('input_context', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('raw_response', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='missions.mission')),
                ('telemetry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analyses', to='telemetry.telemetry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
