# Generated by Django 6.0.7 on 2026-08-03 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsystem', models.CharField(choices=[('THERMAL', 'Thermal Control'), ('ELECTRICAL', 'Electrical Power'), ('COMMUNICATION', 'Communication'), ('PROPULSION', 'Propulsion'), ('RADIATION', 'Radiation Protection'), ('ENVIRONMENTAL', 'Environmental Control'), ('NAVIGATION', 'Navigation'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('description', models.TextField()),
                ('recommended_action', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved')], default='NEW', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='missions.mission')),
                ('telemetry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='telemetry.telemetry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
