import sys, os, django
sys.path.insert(0, 'SpaceGuard-AI/backend')
os.environ['DJANGO_SETTINGS_MODULE'] = 'spaceguard.settings'
django.setup()

from missions.models import Mission
from ai.pipeline import run_analysis_pipeline

m = Mission.objects.get(spacecraft_name='ISS-Alpha')
t = m.telemetry_records.order_by('-timestamp').first()
result = run_analysis_pipeline(t)

health = result['health']
anomaly = result['anomaly']
explanation = result['explanation']
predictions = result['predictions']

print('=== SPACEGUARD AI ANALYSIS RESULT ===')
print(f'Health Score : {health["health_score"]}/100')
print(f'Risk Level   : {health["risk_level"]}')
print(f'Category     : {health["health_category"]}')
print(f'Score Breakdown: {health["score_breakdown"]}')
print()
print(f'Anomaly      : {anomaly["is_anomaly"]}')
print(f'Severity     : {anomaly["severity"]}')
print(f'Subsystem    : {anomaly["affected_subsystem"]}')
print(f'Score        : {anomaly["anomaly_score"]}')
print(f'Suspicious   : {anomaly["suspicious_parameters"]}')
print()
print(f'Generated by : {explanation["generated_by"]}')
print(f'Problem      : {str(explanation["detected_problem"])[:100]}')
print(f'Action       : {str(explanation["recommended_action"])[:100]}')
print()
for p in predictions[:3]:
    w = p.get('warning_message', '')
    if w:
        print(f'WARNING: {w[:100]}')
    else:
        print(f'Trend [{p["parameter"]}]: {p["trend_direction"]} -> {p["predicted_value"]}')

from alerts.models import Alert
print()
print(f'Total Alerts : {Alert.objects.count()}')
from anomaly.models import AIAnalysis
print(f'AI Analyses  : {AIAnalysis.objects.count()}')
