# Generated by Django 6.0.7 on 2026-08-03 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('temperature', models.FloatField(help_text='Degrees Celsius')),
                ('battery_voltage', models.FloatField(help_text='Volts')),
                ('battery_current', models.FloatField(help_text='Amperes')),
                ('fuel_level', models.FloatField(help_text='Percentage 0-100')),
                ('radiation', models.FloatField(help_text='mSv')),
                ('pressure', models.FloatField(help_text='kPa')),
                ('signal_strength', models.FloatField(help_text='dBm')),
                ('velocity', models.FloatField(help_text='km/s')),
                ('power_consumption', models.FloatField(help_text='Watts')),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_records', to='missions.mission')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['mission', 'timestamp'], name='telemetry_t_mission_25ec79_idx')],
            },
        ),
    ]
